apiVersion: v1
kind: Service
metadata:
    name: "kingoliver-03c2"
    labels:
        app: "kingoliver-03c2"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kingoliver-03c2"